services:
  walletx_db:
    image: postgres:17-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - walletx_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  app:
    build: .
    restart: always
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8038:8000"
    depends_on:
      - walletx_db

volumes:
  walletx_data:
