[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]  # Enable rules (E = style errors, F = flakes, I = imports)
ignore = ["E501"]  # Ignore long line warnings

[tool.ruff.format]
quote-style = "double"  # Use double quotes
